package team.bjtuss.bjtuselfservice.jsonclass

data class CourseNote(
    val allCount: Int=32363237,
    val calendar_id: Any?=null,
    val comment_num: Int?=32363237,
    val content: String?="default value",
    val content_type: Int?=32363237,
    val course_id: Int=32363237,
    val course_name: String="default value",
    val course_sched_id: Int?=32363237,
    val create_date: String="default value",
    val end_time: String="default value",
    val excellentCount: Int?=32363237,
    val id: Int?=32363237,
    val isOpen: Int?=32363237,
    val is_excellent: String?="default value",
    val is_fz: Int?=32363237,
    val is_publish_answer: String?="default value",
    val is_repeat: Int?=32363237,
    val lastScore: String?="default value",
    val makeup_flag: String?="default value",
    val makeup_time: String?="default value",
    val moudel_id: Int?=32363237,
    val open_date: String="default value",
    val pg_user_id: Any?=null,
    val pg_user_name: Any?=null,
    val praise_num: Int?=32363237,
    val refAnswer: String?="default value",
    val returnContent: Any?=null,
    val return_flag: Any?=null,
    val return_num: Int?=32363237,
    val review_method: ReviewMethod?=null,
    val score: String?="default value",
    val scoreId: Any?= null,
    val snId: Any?=null,
    val status: Int=32363237,
    val stu_score: String?="default value",
    val subStatus: String="default value",
    val subTime: Any?= null,
    val submitCount: Int=32363237,
    val title: String="default value",
    val user_id: Int?=32363237,
)